name: Next Js Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  build:
    name: Next.js Incremental static Generate every hour
    runs-on: ubuntu-latest
    steps:
      - name: cURL request on website
        run: |
          curl https://covid19-updates.vercel.app/
          curl -X POST -d "email=${{ secrets.ADMIN_EMAIL }}&password=${{ secrets.ADMIN_PASSWORD }}" https://www.sarwisi.com/api/credits/currency/update/rate/