name: Next Js Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  build:
    name: Next.js Incremental static Generate every hour
    runs-on: ubuntu-latest
    steps:
      - name: cURL request on website
      - uses: actions/checkout@v3
        run: |
          curl https://covid19-updates.vercel.app/